name: dog_adoption_app
description: A Flutter web application for dog adoption management.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: ^2.3.0
  sqflite_common_ffi_web: ^0.4.0+1
  path: ^1.8.3
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  universal_html: ^2.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
